POST http://localhost:5000/move
Content-Type: application/json

{
    "human": 1,
    "ai": 2,
    "column": 3,
    "board": [
      [0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0],
      [0,0,0,0,1,0,0]
    ]
}